name: Hello World
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: build step
        run:  echo "A build Job"
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test step
        run: echo "Runuing test case"
  deploy:
     runs-on: ubuntu-latest
     steps:
       - name: Deploymber
         run: echo "running deployment steps"
