name: Hello World
# on: workflow_dispatch  # manual trigger
on: 
  push:
    branches:
      - main
      - devlop
      - 'release/**'
  
  pull_request:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: build step
        run:  echo "A build Job"
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Test step
        run: echo "Runuing test case"
  deploy:
     runs-on: ubuntu-latest
     needs: test  # create dependency
     steps:
       - name: Deploymber
         run: echo "running deployment steps"
