name: Checkout-action
on: workflow_dispatch
jobs:
  checkout:
    runs-on: ubuntu_latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Print Index.html
        run: cat index.html