name: Input deployment
on: 
  workflow_dispatch:
    inputs:
      environment:
         description: Choose the env to deploy
         required: true
         default: dev

jobs:
  input-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to env
        run: echo "run on ${{ .inputs.environment }}"